"""empty message

Revision ID: 210aa760d3d1
Revises: 79fb1c5b539b
Create Date: 2019-03-08 19:15:49.057612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '210aa760d3d1'
down_revision = '79fb1c5b539b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_chat',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('logo', sa.String(length=100), nullable=True),
    sa.Column('chat_obj_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_chatmessage',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('messages')
    op.drop_table('t_groupsmsgcontent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_groupsmsgcontent',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('from_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('from_name', mysql.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['t_user.id'], name='t_groupsmsgcontent_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('messages',
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('from_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('to_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message_type', mysql.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['t_user.id'], name='messages_ibfk_1'),
    sa.ForeignKeyConstraint(['to_id'], ['t_user.id'], name='messages_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('t_chatmessage')
    op.drop_table('t_chat')
    # ### end Alembic commands ###
