"""empty message

Revision ID: 4a3faed832a3
Revises: e54d817e24e8
Create Date: 2019-02-13 11:15:01.560749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a3faed832a3'
down_revision = 'e54d817e24e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('is_admin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'is_admin')
    # ### end Alembic commands ###
