"""empty message

Revision ID: 9e110cfad0ef
Revises: 1f256d2bf48a
Create Date: 2019-02-13 15:49:21.280011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e110cfad0ef'
down_revision = '1f256d2bf48a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_group', sa.Column('logo', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_group', 'logo')
    # ### end Alembic commands ###
